package au.gov.amsa.ihs.reader;

public enum Key {
    //
    LRIMOShipNo,
    //
    AlterationsDescriptiveNarrative,
    //
    AuxilaryGeneratorsDescriptiveNarrative,
    //
    AuxiliaryEnginesNarrative,
    //
    BaleCapacity,
    //
    BoilersDescriptiveNarrative,
    //
    BollardPull,
    //
    BowDischargeFacility,
    //
    BowLoadingFacility,
    //
    Breadth,
    //
    BreadthExtreme,
    //
    BreadthMoulded,
    //
    BunkersDescriptiveNarrative,
    //
    CallSign,
    //
    CargoCapacitiesNarrative,
    //
    CargoTankCoatings,
    //
    ChartererLatestReported,
    //
    ClassNarrative,
    //
    ClassificationSocietyCode,
    //
    ClosedLoadingSystem,
    //
    ConstructionDescriptiveNarrative,
    //
    ContractDate,
    //
    CountryOfBreaking,
    //
    CountryOfBuild,
    //
    CountryOfBuildCode,
    //
    CrudeOilWashingCOW,
    //
    DateBreakingCommenced,
    //
    Deadweight,
    //
    DeathDate,
    //
    DeliveryDate,
    //
    DateOfBuild,
    //
    Depth,
    //
    Displacement,
    //
    Draught,
    //
    FairplayID,
    //
    FlagCode,
    //
    FlagEffectiveDate,
    //
    FlagName,
    //
    FlashPointOver60c,
    //
    FlashPointUnder60c,
    //
    FormulaDWT,
    //
    FuelType1Capacity,
    //
    FuelType1First,
    //
    FuelType2Capacity,
    //
    FuelType2Second,
    //
    GasCapacity,
    //
    GearDescriptiveNarrative,
    //
    Gearless,
    //
    GrainCapacity,
    //
    GrossTonnage,
    //
    GroupBeneficialOwner,
    //
    GroupBeneficialOwnerCompanyCode,
    //
    GroupBeneficialOwnerCountryOfControl,
    //
    GroupBeneficialOwnerCountryofDomicile,
    //
    GroupBeneficialOwnerCountryofDomicileCode,
    //
    GroupBeneficialOwnerCountryOfRegistration,
    //
    HatchesDescriptiveNarrative,
    //
    HoldsDescriptiveNarrative,
    //
    HullMaterial,
    //
    HullMaterialCode,
    //
    HullType,
    //
    HullTypeCode,
    //
    IceCapabilityDescriptiveNarrative,
    //
    IMOChemicalClassI,
    //
    IMOChemicalClassII,
    //
    IMOChemicalClassIII,
    //
    InertGasSystemIGS,
    //
    InmarsatNumberSatCommID,
    //
    InsulatedCapacity,
    //
    KeelLaidDate,
    //
    LanesDoorsRampsNarrative,
    //
    LastUpdateDate,
    //
    LaunchDate,
    //
    LeadshipinseriesbyIMONumber,
    //
    LengthBetweenPerpendicularsLBP,
    //
    LengthOverallLOA,
    //
    LengthRegistered,
    //
    LightDisplacementTonnage,
    //
    LiquidCapacity,
    //
    MainEngineBuilder,
    //
    MainEngineBuilderCode,
    //
    MainEngineDesignerCode,
    //
    MainEngineModel,
    //
    MainEngineNumberofCylinders,
    //
    MainEngineRPM,
    //
    MainEngineStrokeType,
    //
    MainEngineType,
    //
    MaritimeMobileServiceIdentityMMSINumber,
    //
    MARPOL13GPhaseoutCategory,
    //
    NetTonnage,
    //
    NumberOfAuxiliaryEngines,
    //
    NumberofCabins,
    //
    NumberofDecks,
    //
    NumberofHatches,
    //
    NumberofHolds,
    //
    NumberofMainEngines,
    //
    NumberOfPropulsionUnits,
    //
    NumberofTanks,
    //
    OfficialNumber,
    //
    PanamaCanalNetTonnagePCNT,
    //
    PandIClub,
    //
    PandIClubCode,
    //
    PassengerCapacity,
    //
    PermanentBallastCapacity,
    //
    PhotoPresent,
    //
    PortofRegistry,
    //
    PortofRegistryFullCode,
    //
    PrimeMoverDescriptiveNarrative,
    //
    PrimeMoverDescriptiveOverviewNarrative,
    //
    PropellerType,
    //
    PropulsionType,
    //
    PropulsionTypeCode,
    //
    ReeferPoints,
    //
    SafetyManagementCertificateAuditor,
    //
    SafetyManagementCertificateDateExpires,
    //
    SafetyManagementCertificateDateIssued,
    //
    SafetyManagementCertificateIssuer,
    //
    SafetyManagementCertificateShipType,
    //
    SegregatedBallastCapacity,
    //
    ShipName,
    //
    ShipStatus,
    //
    ShipStatusCode,
    //
    ShipStatusEffectiveDate,
    //
    Shipbuilder,
    //
    ShipbuilderCompanyCode,
    //
    ShipbuilderFullStyle,
    //
    ShiptypeGroup,
    //
    SlopTankCapacity,
    //
    SpecialTanksDescriptiveNarrative,
    //
    Speed,
    //
    StandardShipDesign,
    //
    StatCode5,
    //
    TanksDescriptiveNarrative,
    //
    TEU,
    //
    TEUCapacity14tHomogenous,
    //
    ThrustersDescriptiveNarrative,
    //
    TotalKilowattsofMainEngines,
    //
    TotalPowerOfAllEngines,
    //
    TotalPowerOfAuxiliaryEngines,
    //
    VapourRecoverySystem,
    //
    YardNumber,
    //
    RegisteredOwnerCode,
    //
    DocumentofComplianceDOCCompanyCode,
    //
    ShiptypeLevel2,
    //
    ShiptypeLevel3,
    //
    ShiptypeLevel4,
    //
    ShiptypeLevel5,
    //
    ShiptypeLevel5HullType,
    //
    ShiptypeLevel5SubGroup,
    //
    ShiptypeLevel5SubType;
}
