package au.gov.amsa.risky.format;

public enum NavigationalStatus {
 UNDER_WAY_USING_ENGINE,AT_ANCHOR,NOT_UNDER_COMMAND,RESTRICTED_MANOEUVRABILITY,CONSTRAINED_BY_HER_DRAUGHT,MOORED, AGROUND, ENGAGED_IN_FISHING, UNDER_WAY;
}
