# This workflow will build a GitHub published release of a Java project with Maven, sign the artifacts and deploy them to Maven\
# Central (Sonatype Open Source Software Repository Hosting (OSSRH))
#
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: DeployReleaseToMavenCentral

on:
  release:
    types: [ published ]


jobs:
  build:
    name: Deploy release
    uses: amsa-code/.github/.github/workflows/deploy-release-to-maven-central.yaml@master
