package au.gov.amsa.ais.rx;

public enum CraftPropertyName {
	DESTINATION, DIMENSION_A, DIMENSION_B, DIMENSION_C, DIMENSION_D, NAME, IMO_NUMBER, CALLSIGN, LENGTH_METRES, SHIP_TYPE, WIDTH_METRES, DRAUGHT_METRES;
}
